# Generated by Django 5.2.4 on 2025-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Single Line Text'), ('TEXTAREA', 'Multi-line Text'), ('NUMBER', 'Number'), ('CHOICE', 'Multiple Choice')], default='TEXT', max_length=10),
        ),
    ]
